CREATE TABLE reporting_results2020 (
    id SERIAL PRIMARY KEY,
    numer_ewidencyjny_system TEXT,
    numer_ewidencyjny_urzad TEXT,
    data_wplywu_wniosku_do_urzedu TIMESTAMP,
    nazwa_organu TEXT,
    wojewodztwo_objekt TEXT,
    obiekt_kod_pocztowy TEXT,
    miasto TEXT,
    terc TEXT,
    cecha TEXT,
    cecha2 TEXT,
    ulica TEXT,
    ulica_dalej TEXT,
    nr_domu TEXT,
    kategoria TEXT,
    nazwa_zam_budowlanego TEXT,
    rodzaj_zam_budowlanego TEXT,
    kubatura TEXT,
    stan TEXT,
    jednostki_numer TEXT,
    obreb_numer TEXT,
    numer_dzialki TEXT,
    numer_arkusza_dzialki TEXT,
    nazwisko_projektanta TEXT,
    imie_projektanta TEXT,
    projektant_numer_uprawnien TEXT,
    projektant_pozostali TEXT
);